remove unnecessary nullable flag (#1)
usox/hackmock pull request #2
Opened 2018-10-19 19:36 UTC by ivyhjk

2018-10-20 11:50 UTC, usox requested changes

2018-10-20 11:50 UTC, usox commented on tests/UntipedSampleTest.hh
> +use HH\Lib\Str;
Please remove unused imports.

2018-10-20 11:50 UTC, usox commented on tests/UntipedSampleTest.hh
> +class UntipedSampleTest extends \Usox\HackMock\HackMock {
I guess you mean `Untyped`

2018-10-21 02:16 UTC, ivyhjk reviewed
Done!

2018-10-21 07:26 UTC, usox commented
I will perform some further tests tomorrow on some other code at work. If it works out, this will be released within a patch level release this week.

2018-10-21 12:42 UTC, ivyhjk commented
Thanks!

2018-10-22 06:37 UTC, merged

2018-10-22 06:40 UTC, usox commented
Excellent github, rebase and merge doesn't work all too good... Your Code has been merged, but github had some internal issues while rebasing/merging it